import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Toolbar from "./components/Toolbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Toolbar />
          <div className="relative w-full">
            <img src="/hero.png" className="hero-image" alt="Hero" />
            <img src="/logo.svg" className="hero-logo" alt="Logo" />
          </div>
        <div className="mx-40">
          {children}
        </div>
      </body>
    </html>
  );
}
