import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import Toolbar from "./components/Toolbar";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	weight: ["400", "700", "800"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
	weight: ["400", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${geistMono.variable} text-sm antialiased md:text-base`}>
				<Toolbar />
				<div className="relative w-full">
					<img src="/hero.png" className="m-0 block h-auto w-full" alt="Hero" />
					<img
						src="/logo.svg"
						className="pointer-events-none absolute top-4 left-4 z-10 h-20 w-auto"
						alt="Logo"
					/>
				</div>
				<main className="mx-10 md:mx-20 lg:mx-40">{children}</main>
			</body>
		</html>
	);
}
